### ISSUE TITLE
Willow trees don't have the willow vines

### ISSUE THREAD

**Issue by mosharky** [joe-vettek/Dynamic-Trees-for-Natures-Spirit#1]

**Comment by joe-vettek** [comment]
You didn't say anything, so I can't know the details.

**Comment by joe-vettek** [comment]
![image](https://github.com/user-attachments/assets/df5733e7-74bd-4775-9914-a65e8d54ced2)

It was working fine when I wrote this mod before.

**Comment by mosharky** [comment]
I'm talking about willow trees, not wisteria. They're missing their vines:
![image](https://github.com/user-attachments/assets/ce06ee77-fa52-49e6-8f06-f630f8b53305)

**Comment by mosharky** [comment]
This is what willow looks like w/o dynamic trees:
![image](https://github.com/user-attachments/assets/f570e4aa-892b-4434-9741-b7ac6cdaec24)

**Comment by joe-vettek** [comment]
![image](https://github.com/user-attachments/assets/5fd69daa-6f3b-436e-8972-fc90ce7c4e4a)
I'm not sure if I'm seeing things.

**Comment by mosharky** [comment]
Maybe it's the other mods I have? This is my mod list:
- Connector Extras
- Dynamic Trees
- Dynamic Trees Plus
- Dynamic Trees for Nature's Spirit
- Embeddium
- Ferrite Core
- Forgified Fabric API
- ImmediatelyFast
- ModernFix
- Nature's Spirit
- REI Plugin Compatibilities
- Roughly Enough Items \(REI\)
- Sinytra Connector
- TerraBlender
- TerraBlenderFix

**Comment by mosharky** [comment]
Oops I just realized you zoomed in on the image I sent. Not sure how I missed that, sorry!
